2018-05-13 20:16:16,089 - __main__ - INFO - 用户登录成功！
2018-05-13 20:16:40,242 - __main__ - INFO - 用户登录成功！
2018-05-14 12:19:36,545 - __main__ - INFO - 用户登录成功！
2018-05-14 12:23:39,390 - __main__ - INFO - 用户名不存在！
2018-05-14 12:23:50,254 - __main__ - ERROR - 用户密码连续输入错误3次，账号已锁定，请联系系统管理员解锁。
2018-05-14 12:43:56,199 - __main__ - INFO - 用户登录成功！
2018-05-14 12:44:05,758 - __main__ - ERROR - 用户密码连续输入错误3次，账号已锁定，请联系系统管理员解锁。
2018-05-14 13:12:41,785 - __main__ - INFO - 用户名不存在！
2018-05-14 13:12:41,785 - __main__ - ERROR - exception
Traceback (most recent call last):
  File "C:/Users/chinalife/Documents/mypython/task2_login/bin/login.py", line 85, in <module>
    raise Exception
Exception
